- name: docker build and push
  hosts: 13.233.173.17  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t pipeline .

    - name: tag image
      command: docker tag pipeline:latest virat/pipeline:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: manoj3214
        password: Manoj321@

    - name: Push image
      command: docker push virat/pipeline:latest

    - name: Run container
      command: docker run -d --name p
